import { NgModule } from '@angular/core';
import {ScrollingModule} from '@angular/cdk/scrolling';
import { MatMomentDateModule } from "@angular/material-moment-adapter"
import {
  MatRippleModule,
  MatCheckboxModule,
  MatButtonModule,
  MatInputModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatFormFieldModule,
  MatRadioModule,
  MatSelectModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatSidenavModule,
  MatToolbarModule,
  MatListModule,
  MatGridListModule,
  MatCardModule,
  MatStepperModule,
  MatTabsModule,
  MatExpansionModule,
  MatButtonToggleModule,
  MatChipsModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatDialogModule,
  MatTooltipModule,
  MatSnackBarModule,
  MatTableModule,
  MatSortModule,
  MatPaginatorModule,
  MatNativeDateModule,
  MatDividerModule

} from '@angular/material';


@NgModule({
  // imports: [
  //   MatRippleModule,
  //   MatCheckboxModule,
  //   MatButtonModule,
  //   MatInputModule,
  //   MatAutocompleteModule,
  //   MatDatepickerModule,
  //   MatFormFieldModule,
  //   MatRadioModule,
  //   MatSelectModule,
  //   MatSliderModule,
  //   MatSlideToggleModule,
  //   MatMenuModule,
  //   MatSidenavModule,
  //   MatToolbarModule,
  //   MatListModule,
  //   MatGridListModule,
  //   MatCardModule,
  //   MatStepperModule,
  //   MatTabsModule,
  //   MatExpansionModule,
  //   MatButtonToggleModule,
  //   MatChipsModule,
  //   MatIconModule,
  //   MatProgressSpinnerModule,
  //   MatProgressBarModule,
  //   MatDialogModule,
  //   MatTooltipModule,
  //   MatSnackBarModule,
  //   MatTableModule,
  //   MatSortModule,
  //   MatPaginatorModule,
  //   MatNativeDateModule,
  //   MatMomentDateModule,
  //   MatDividerModule
    
  // ],
  exports: [
    MatRippleModule,
    MatCheckboxModule,
    MatButtonModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatRadioModule,
    MatSelectModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatStepperModule,
    MatTabsModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatNativeDateModule,
    MatMomentDateModule,
    MatDividerModule,
    ScrollingModule
  ]
})
export class MaterialAngularModule { }